### ISSUE TITLE
mangrove disturbance alerts no longer filtered when selecting a country

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#380]
When I select a country, the mangrove disturbance alerts widget doesn't respond. It just always show the total number of disturbances wordwide

![image](https://user-images.githubusercontent.com/3919721/162639209-fe67af66-8640-4af6-a3a5-ae6fcb7ad498.png)

**Comment by dhakelila** [comment]
@mluena , can you take a look?

**Comment by klongleywood** [comment]
FYI @lhilarides @dhakelila @mluena  this is still an issue. Our training consultant would like to do a live demo of this feature at the GMW workshop on the morning of May 10th -- is there any chance this could be fixed by then?

**Comment by dhakelila** [comment]
@klongleywood we are working on it right now. It should be fixed by the 10th.

**Comment by klongleywood** [comment]
@mluena thanks for looking into this. I see that the bug was fixed in the widget, but now the alerts are not showing up on the map. Is this something you're still working on?

**Comment by mluena** [comment]
you should be able to see everything (including safari, let me know if it's not the case)

**Comment by klongleywood** [comment]
Sorry @mluena but I still can't see the alerts show up on the map. I'm in Chrome and I've cleared my cache.
